/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package org.lenguajesFP.Frontend;

import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.lenguajesFP.Backend.Reader;
import org.lenguajesFP.Backend.Writer;
import org.lenguajesFP.Backend.exceptions.LexicalAnalyzerException;
import org.lenguajesFP.Backend.reports.ReportsGenerator;

/**
 *
 * @author brigidoalvarado
 */
public class LexicalsWebAnalyzerApp extends javax.swing.JFrame {

    private String input;
    private Writer writer = new Writer();

    /**
     * Creates new form LexicalsWebAnalyzerApp
     */
    public LexicalsWebAnalyzerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerjPnl = new javax.swing.JPanel();
        generatejBttn = new javax.swing.JButton();
        optimizejBttn = new javax.swing.JButton();
        exportjBttn = new javax.swing.JButton();
        textAreasContainerjPnl = new javax.swing.JPanel();
        jScrllPnInput = new javax.swing.JScrollPane();
        InputjTxtAr = new javax.swing.JTextArea();
        jScrllPnlOutput = new javax.swing.JScrollPane();
        OutputjTxtAr = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        reportsFileMenu = new javax.swing.JMenu();
        tokensReportsMnItm = new javax.swing.JMenuItem();
        errorsReportMnItm = new javax.swing.JMenuItem();
        optimizeReportsMnItm = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generatejBttn.setText("TRADUCIR");
        generatejBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatejBttnActionPerformed(evt);
            }
        });

        optimizejBttn.setText("OPTIMIZAR");
        optimizejBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimizejBttnActionPerformed(evt);
            }
        });

        exportjBttn.setText("GENERAR HTML");
        exportjBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportjBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerjPnlLayout = new javax.swing.GroupLayout(containerjPnl);
        containerjPnl.setLayout(containerjPnlLayout);
        containerjPnlLayout.setHorizontalGroup(
            containerjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerjPnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(generatejBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optimizejBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportjBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        containerjPnlLayout.setVerticalGroup(
            containerjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerjPnlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(containerjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatejBttn)
                    .addComponent(optimizejBttn)
                    .addComponent(exportjBttn))
                .addGap(9, 9, 9))
        );

        getContentPane().add(containerjPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 50));

        textAreasContainerjPnl.setBackground(new java.awt.Color(245, 245, 245));
        textAreasContainerjPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputjTxtAr.setColumns(20);
        InputjTxtAr.setRows(5);
        InputjTxtAr.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                InputjTxtArCaretUpdate(evt);
            }
        });
        jScrllPnInput.setViewportView(InputjTxtAr);

        textAreasContainerjPnl.add(jScrllPnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 480));

        OutputjTxtAr.setEditable(false);
        OutputjTxtAr.setColumns(20);
        OutputjTxtAr.setRows(5);
        OutputjTxtAr.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                OutputjTxtArCaretUpdate(evt);
            }
        });
        jScrllPnlOutput.setViewportView(OutputjTxtAr);

        textAreasContainerjPnl.add(jScrllPnlOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 550, 480));

        getContentPane().add(textAreasContainerjPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1130, 520));

        reportsFileMenu.setMnemonic('f');
        reportsFileMenu.setText("Reportes");

        tokensReportsMnItm.setMnemonic('o');
        tokensReportsMnItm.setText("Reporte de Tokens");
        tokensReportsMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokensReportsMnItmActionPerformed(evt);
            }
        });
        reportsFileMenu.add(tokensReportsMnItm);

        errorsReportMnItm.setMnemonic('s');
        errorsReportMnItm.setText("Reporte de Errores");
        errorsReportMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorsReportMnItmActionPerformed(evt);
            }
        });
        reportsFileMenu.add(errorsReportMnItm);

        optimizeReportsMnItm.setMnemonic('a');
        optimizeReportsMnItm.setText("Reporte de Optimizacion");
        optimizeReportsMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimizeReportsMnItmActionPerformed(evt);
            }
        });
        reportsFileMenu.add(optimizeReportsMnItm);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        reportsFileMenu.add(exitMenuItem);

        menuBar.add(reportsFileMenu);

        helpMenu.setMnemonic('h');

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void InputjTxtArCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_InputjTxtArCaretUpdate
        // TODO add your handling code here
        input = InputjTxtAr.getText();
    }//GEN-LAST:event_InputjTxtArCaretUpdate

    private void generatejBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatejBttnActionPerformed
        // TODO add your handling code here:
        try {
            OutputjTxtAr.setText(writer.generateAndTranslate(input + "\n   "));
        } catch (LexicalAnalyzerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error el texto ingresado", e.getMessage(), JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Para traducir primero ingrese datos en el area de texto", "SIN DATOS", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_generatejBttnActionPerformed

    private void OutputjTxtArCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_OutputjTxtArCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputjTxtArCaretUpdate

    private void optimizejBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimizejBttnActionPerformed
        // TODO add your handling code here:
        try {
            OutputjTxtAr.setText(writer.optimize());
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Para optimizar primero debe traducir su codigo", "DATOS SIN TRADUCIR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_optimizejBttnActionPerformed

    private void exportjBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportjBttnActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = fileChooser.showOpenDialog(this);
            if (selection == JFileChooser.APPROVE_OPTION) {
                writer.export(fileChooser.getSelectedFile().getAbsolutePath(), "Html-Generado");
            }
        } catch (LexicalAnalyzerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se puede exportar un html sin haber optimizado el codigo primero", "Sin Optimizar", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_exportjBttnActionPerformed

    private void tokensReportsMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokensReportsMnItmActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = fileChooser.showOpenDialog(this);
            if (selection == JFileChooser.APPROVE_OPTION) {
                ReportsGenerator reportsGenerator = new ReportsGenerator();
                String outputPath = reportsGenerator.TokensReport(writer.getReader().getTokens(),fileChooser.getSelectedFile().getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Se guardo el archivo de reportes en \n" + outputPath, "Reporte generado exitosamente", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (LexicalAnalyzerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al reportar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tokensReportsMnItmActionPerformed

    private void errorsReportMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorsReportMnItmActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = fileChooser.showOpenDialog(this);
            if (selection == JFileChooser.APPROVE_OPTION) {
                ReportsGenerator reportsGenerator = new ReportsGenerator();
                String outputPath = reportsGenerator.ErrorsReport(writer.getReader().getErrors(),fileChooser.getSelectedFile().getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Se guardo el archivo de reportes de errores en \n" + outputPath, "Reporte generado exitosamente", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (LexicalAnalyzerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al reportar los errores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_errorsReportMnItmActionPerformed

    private void optimizeReportsMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimizeReportsMnItmActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = fileChooser.showOpenDialog(this);
            if (selection == JFileChooser.APPROVE_OPTION) {
                ReportsGenerator reportsGenerator = new ReportsGenerator();
                String outputPath = reportsGenerator.optimizeReports(writer.getReader().getTokens(),fileChooser.getSelectedFile().getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Se guardo el archivo de reportes de optimizacion en \n" + outputPath, "Reporte generado exitosamente", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (LexicalAnalyzerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al reportar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_optimizeReportsMnItmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LexicalsWebAnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LexicalsWebAnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LexicalsWebAnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LexicalsWebAnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LexicalsWebAnalyzerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InputjTxtAr;
    private javax.swing.JTextArea OutputjTxtAr;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel containerjPnl;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem errorsReportMnItm;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton exportjBttn;
    private javax.swing.JButton generatejBttn;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrllPnInput;
    private javax.swing.JScrollPane jScrllPnlOutput;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem optimizeReportsMnItm;
    private javax.swing.JButton optimizejBttn;
    private javax.swing.JMenu reportsFileMenu;
    private javax.swing.JPanel textAreasContainerjPnl;
    private javax.swing.JMenuItem tokensReportsMnItm;
    // End of variables declaration//GEN-END:variables

}
